config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resource :event, only: :show
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def show
    @username = params[:username]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/events/show.html.erb
<h1><%= @username %>'s GitHub Events!</h1>
<label name="github-username" id="<%= @username %>" style="display:none;"></label>

<div id="github-events">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gvents</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag params[:controller] %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag params[:controller] %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<div class="container">
  <div class="row row-centered vcenter">
    <h3>Welcome to Gvents!</h3>

    <%= render 'shared/events/username_submit_form' %>
  </div>
</div>

app/views/shared/events/_username_submit_form.html.erb
<%= form_tag event_path, method: :get do %>
  <div class="form-group">
    <div class="col-sm-4 col-centered">
      <%= text_field_tag 'username', nil,
        class: 'form-control', id: 'myInput', required: true,
        placeholder: 'Enter your GitHub Username' %>
    </div>
  </div>

  <%= submit_tag 'Submit', class: 'btn btn-default', name: nil %>
<% end %>